#!/usr/bin/python
# -*- coding: utf-8 -*-
# 接口测试用例模板
import pytest
import allure
from common.handleLog import log
from common.handleCases import handle_case
from common.handleYaml import read_yaml
from conf.projectPath import *
test_datas=read_yaml(os.path.join(projects_path,r"{{case_item['data_file_path']}}"))
@allure.feature("{{case_item['report_name']}}")
@pytest.mark.flyback
@pytest.mark.usefixture('setUp_tearDown')
class TestCase:
    def {{case_item['case_name']}}(self,data,setUp_tearDown):
        with allure.step(data['title']):
            data['token'] = setUp_tearDown
            actually_result = handle_case(data)
            try:
                assert actually_result == True
            except Exception as e:
                log.debug(f"用例{data['title']}未通过: 报错为{e}")
                raise e
